project:
  name: "Auroral Geomagnetic Index Prediction"
  author: "Yerko Jelcic"
  version: 4
  seed: 42

  logging: True
  plot: True

dataset:
  time_range:
    start: "1995-01-01"
    end: "2018-03-01"
  
  omni_list: [
    "B_T",
    "BZ_GSE",
    "BZ_GSM",
    "flow_speed",
    "Vx",
    "T",
    "Pressure",
    "E"
  ]

  auroral_index: ["AE_INDEX"]

  calculate: [
    "epsilon",
    "E_kl",
    "dPhi_dt"
  ]

interpolation:
  benchmark: True
  method: auto      # auto | pchip | iterative | gp | best
  umbral_corto: 15
  n_bins: 4
  n_gaps_por_repeticion: 40

scaling:
  method: standard    # standard | robust | minmax


model:
  type: False
